# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 470e9204d716098c284076cb8ca82a6dbf9bbc10bbc83b6f84b90060f0adcbefc143773ac895e74b3734aa1f845037a2fc2940967ed2d14a26c0408131ebe9ff

test:
  secret_key_base: dcca82fce2edb3f1444544b5adea088c355ae0d41e699229a11a408f7aa854f0fd03d00d058559063bbc40d9a46b64639119254eed2928289b62bc9424846961

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
