# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci



# local
development:
  <<: *default
  database: lazycalculus
  password: 123123

production:
  <<: *default
  #TODO CONFIG
  #database: production_real
  #host: real-production.copzu9uynnvm.us-west-2.rds.amazonaws.com
  #username: prod
  #password: tDB!#%135